// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgrkwbbqvpoiomvxgxmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJncmt3YmJxdnBvaW9tdnhneG16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NjMzOTIsImV4cCI6MjA3MTEzOTM5Mn0.-sM7QWwZ86iqnPZortmNjwkYASQ1EfOFDUkA0WUSoa8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});